account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    path('', views.index, name='index'),
    path('signup/', views.user_signup, name='signup'),
    path('activate_user/<uuid:token>/', views.activate_user, name='activate_user'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('withdrawal/', views.user_withdrawal, name='withdrawal'),

    path('email/', views.user_email, name='email'),
    path('password/', views.user_password, name='password'),

    path('profile', views.user_profile, name='profile'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.post_create, name='new'),
    path('detail/<int:pk>/', views.post_detail, name='detail'),
    path('detail/<int:pk>/edit', views.post_edit, name='edit'),
    path('detail/<int:pk>/delete', views.post_delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/flash_messages.html
{% if messages %}
{% for message in messages %}
<ul class="messages list-unstyled">
    <li{% if message.tags %} class="alert alert-{{ message.tags }} text-center"{% endif %} role="alert">
        {{ message.message }}
    </li>
</ul>
{% endfor %}
{% endif %}

templates/snippets/header_nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'blog:index' %}">Blog</a>
        <ul class="navbar-nav ml-auto">



            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:index' %}">投稿一覧</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:new' %}">新規投稿</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button"
                    data-bs-toggle="dropdown" aria-expanded="false">
                    ユーザー設定
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <li><a class="dropdown-item" href="{% url 'account:profile' %}">プロフィール設定</a></li>
                    <li><a class="dropdown-item" href="{% url 'account:email' %}">メールアドレス設定</a></li>
                    <li><a class="dropdown-item" href="{% url 'account:password' %}">パスワード設定</a></li>
                    <li><a class="dropdown-item" href="{% url 'account:withdrawal' %}">アカウント削除</a></li>
                </ul>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:logout' %}">ログアウト</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:signup' %}">ユーザー登録</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account:login' %}">ログイン</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>