blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('new', views.post_create, name='new'),
    path('detail/<int:pk>/', views.post_detail, name='detail'),
    path('detail/<int:pk>/edit', views.post_edit, name='edit'),
    path('detail/<int:pk>/delete', views.post_delete, name='delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth import get_user_model
import os

User = get_user_model()

"""
Post
"""
def upload_image_to(instance, filename):
    post_id = str(instance.user.id)
    return os.path.join('blog', 'upload_image', post_id, filename)

class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    title = models.CharField(
        verbose_name='タイトル',
        max_length=30
        )

    content = models.TextField(
        verbose_name='本文',
        max_length=500
        )

    image = models.ImageField(
        verbose_name='投稿画像',
        upload_to=upload_image_to,
        blank=True,
        null=True,
    )

    created_at = models.DateTimeField(
        verbose_name='作成日時',
        auto_now_add=True,
        )

    updated_at = models.DateTimeField(
        verbose_name='更新日時',
        auto_now=True,
        )

    class Meta:
        db_table = 'post'

    def __str__(self):
        return self.title

blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        for field in self.base_fields.values():
            field.widget.attrs["class"] = "form-control mb-3"
        super().__init__(*args, **kwargs)


    class Meta:
        model = Post
        exclude = ['user']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post
from .forms import PostForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def index(request):
    posts = Post.objects.all().order_by('-id')
    return render(request, 'blog/index.html', context={
        'posts': posts
    })


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES or None)

        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, '新規投稿が完了しました')
            return redirect('blog:index')
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', context={
        'form':form,
    })


def post_detail(request,pk):
    post_data = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', context={
        'post_data': post_data,
    })


@login_required
def post_edit(request, pk):
    post_data = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES or None, instance=post_data)

        if form.is_valid():
            form.instance.user = request.user
            form.save()
            messages.success(request, '投稿内容を更新しました')
            return redirect('blog:index')

    else:
        form = PostForm(request.POST or None, instance=post_data)

    return render(request, 'blog/post_form.html', context={
        'form': form,
    })


@login_required
def post_delete(request, pk):
    post_data = get_object_or_404(Post, pk=pk)

    post_data.delete()
    messages.error(request, "投稿を削除しました")
    return redirect('blog:index')

templates/blog/index.html
{% extends 'base.html' %}

{% block title %}投稿一覧{% endblock %}

{% block content %}
<h2 class="my-5 text-center">投稿一覧</h2>


<div class="text-center">
    {% for posts in posts %}
    <div class="card w-50 mx-auto" style="width: 18rem;">
        <p class="card-text my-3">{{ posts.user.profile.username }}</p>
        {% if posts.image %}
        <img src="{{ posts.image.url }}" class="card-img-top w-50 h-50 m-auto" alt="投稿画像">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ posts.title }}</h5>
            <p class="card-text">
                {{ posts.content | truncatechars:20 | linebreaksbr }}<br>
                投稿日: {{ posts.created_at | date:"Y/m/d"}}
            </p>
            <a href="{% url 'blog:detail' pk=posts.pk %}" class="btn btn-primary">詳しく見る</a>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/blog/post_detail.html
{% extends 'base.html' %}

{% block title %}投稿詳細{% endblock %}

{% block content %}
<h2 class="my-5 text-center">投稿詳細</h2>

<div class="text-center">
    <p>タイトル: {{ post_data.title }}</p>
    {% if post_data.image %}
    <img class="w-25 h-25" src="{{ post_data.image.url }}" alt="投稿画像">
    {% endif %}
    <p>本文: <br>{{ post_data.content|linebreaksbr }}</p>
    <p>作成日時: {{ post_data.created_at }}</p>
    <p>更新日時: {{ post_data.updated_at }}</p>
    {% if post_data.user == request.user %}
    <a href="{% url 'blog:edit' post_data.pk %}" class="btn btn-primary">編集</a>
    <a href="{% url 'blog:delete' post_data.pk %}" class="btn btn-danger" onclick="return confirm('{{post_data}} を本当に削除しますか？')">削除</a>
    {% endif %}
</div>
{% endblock %}

templates/blog/post_form.html
{% extends 'base.html' %}

{% block title %}
{% if request.url in 'new' %}
新規投稿
{% else %}
投稿編集
{% endif %}
{% endblock %}

{% block content %}
<div class="mx-auto">
<h2 class="my-5 text-center">
    {% if request.url in 'new' %}
    新規投稿
    {% else %}
    投稿編集
    {% endif %}
</h2>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_table }}
    <div class="text-end">
        <button type="submit" class="btn btn-primary">
            {% if request.url in 'new' %}
            新規投稿
            {% else %}
            更新
            {% endif %}
        </button>
    </div>
</form>
</div>
{% endblock %}